name: deep-learning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python~=3.12.0
  - pytorch~=2.2.2
  - matplotlib~=3.8.4
  - numpy~=1.26.4
  - black~=24.4.2
  - ipython~=8.25.0
  - scikit-learn~=1.5.2
  - pip:
    - matplotlib_inline